package com.mms.demo.entity;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * The Patient class represents a table of the same name in the database. It encapsulates all the
 * information related to a patient that the system accepts. Patients are registered based on unique
 * email addresses.
 * <p>
 * Supports a Builder() as well as a toBuilder(), which are the preferred methods of constructing
 * objects of this class.
 * 
 * @author Mananveer Singh
 */
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Builder(toBuilder = true)
@Entity
@EqualsAndHashCode
@ToString
@Table(name = "PATIENT", schema = "MMSYSTEM")
public class Patient {

    /**
     * The Primary Key. Autogenerated by the DBMS on the creation of an entry.
     *
     */
    @Id
    @Column(name = "patient_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * The full name of the patient.
     * 
     */
    @Column(name = "patient_name", nullable = false)
    private String name;


    /**
     * The gender of the patient. 'M' for male, 'F' for female. Left empty to signify any other.
     * 
     */
    @Column(name = "patient_gender", nullable = true)
    @Pattern(regexp = "M|F")
    private String gender;

    /**
     * The age of the patient.
     *
     */
    @Column(name = "patient_age", nullable = true)
    @Min(0)
    private Integer age;

    /**
     * The email address of the patient.
     * 
     */
    @Column(name = "patient_email", length = 384, unique = true)
    @Email
    private String email;

    /**
     * The phone number of the patient.
     * 
     */
    @Column(name = "patient_phone", length = 14, nullable = true)
    private String phone;

    /**
     * A timestamp marking when the patient was registered.
     */
    @Column(name = "patient_registration_timestamp", nullable = false)
    @Builder.Default
    private LocalDateTime stamp = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);

}
