package com.mms.demo.entity;



import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * The Report class represents a table of the same name in the database. It contains reports,
 * automatically generated at a preset interval, in an Excel format stored as a byte array.
 * <p>
 * Supports a Builder() as well as a toBuilder(), which are the preferred methods of constructing
 * objects of this class.
 * 
 * @author Mananveer Singh
 */
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@Entity
@Builder(toBuilder = true)
@ToString
@Table(name = "REPORT", schema = "MMSYSTEM")
public class Report {
    /**
     * The Primary Key. Autogenerated by the DBMS on the creation of an entry.
     */
    @Id
    @Column(name = "report_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * A timestamp marking the creation time as well as the day covered by the report.
     */
    @Column(name = "report_timestamp")
    @Builder.Default
    private LocalDate stamp = LocalDate.now();

    /**
     * The contents of the report. Contains an XSSF Workbook converted to a byte array.
     * 
     * {@link org.apache.poi.xssf.usermodel.XSSFWorkbook}
     */
    @Lob
    @Column(name = "report_contents", length = 100000)
    private byte[] contents;

}
